server/config/routes.rb
Rails.application.routes.draw do
  get :status, to: proc { [200, {}, ['']] }
  get "/assets/megatron/megatron.css", to: redirect("/assets/megatron/megatron-#{Megatron::VERSION}.css")
  get "/assets/megatron/megatron.js", to: redirect("/assets/megatron/megatron-#{Megatron::VERSION}.js")
  resources :demo, param: :page, path: 'demo'
  resources :errors, param: :page, path: 'errors'
  resources :pages, param: :page, path: ''
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_account

  def current_account
    Struct.new(:slug).new('dummy-account')
  end
end

server/app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def show
    render action: "#{params[:page]}", layout: 'demo'
  end
end

server/app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
    render action: "#{params[:page]}", layout: 'megatron/errors'
  end
end

server/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render action: "#{params[:page]}"
  end
end

server/app/views/demo/index.html.slim
- main do
  - primary_nav do |nav|
    = nav.item 'Clusters', page_path(page: 'deployments'), icon: 'deployment-cluster'
  - secondary_nav do |nav|
    = nav.item 'Test', page_path(page: 'demo'), icon: 'deployment'
    = nav.item 'Secondary', "#", icon: 'bell'
    = nav.item 'Navigation', "#", icon: 'bubble'
    = nav.item 'Icons', "#", icon: 'locked'

  - box_message title: "Preparing your MongoDB deployment"
    .loading-graphic-wrapper
      .loading-graphic
    p.lightgray-text.deployment-status-message This may take a couple minutes.

  form
    input type="range" max="12" value="0" name="vector_deployment[provision_options][units]" data-values="1,2,3,4,5,10,15,20,25,50,75,100,125" data-label-storage="1GB Storage,2GB Storage,3GB Storage,4GB Storage,5GB Storage,10GB Storage,15GB Storage,20GB Storage,25GB Storage,50GB Storage,75GB Storage,100GB Storage,125GB Storage" data-external-label-mongodb-memory="102MB RAM,204MB RAM,306MB RAM,408MB RAM,510MB RAM,1020MB RAM,1.49GB RAM,1.99GB RAM,2.49GB RAM,4.98GB RAM,7.47GB RAM,9.96GB RAM,12.45GB RAM" data-external-label-mongodb-price="$31.00/mo,$49.00/mo,$67.00/mo,$85.00/mo,$103.00/mo,$193.00/mo,$283.00/mo,$373.00/mo,$463.00/mo,$913.00/mo,$1,363.00/mo,$1,813.00/mo,$2,263.00/mo" data-mark="1,4,7,10,13" data-line-labels="1:1GB,13:125GB"

    input type="range" min="0" max="100"

    = slider_input_tag 'range1', after: '%'
    = slider_input_tag 'range2', values: [1, 2, 3], label: [10, 20, 30], before: 'Disk: ', after: ' GB'
    = slider_input_tag 'range35', values: [1, 2, 3], mark: [1, 2, 3], value: 0, labels: { disk: [10, 20, 30], price: ['10.50', '25.50', '30.50'] }, before: { price: '$' }, after: { disk: ' GB Disk' }

server/app/views/layouts/_secondary_nav.slim
- secondary_nav do |nav|
  = nav.item 'Setup', pages_path
  = nav.item 'Navigation', page_path(page: 'navigation')
  = nav.item 'Grids', page_path(page: 'grids')
  = nav.item 'Buttons', page_path(page: 'buttons')
  = nav.item 'Toggler', page_path(page: 'toggler')
  = nav.item 'Icons', page_path(page: 'icons')
  = nav.item 'Forms', page_path(page: 'forms')
  = nav.item 'Color', page_path(page: 'color')

server/app/views/layouts/application.html.slim
= megatron_layout custom_nav: true
  - javascripts do
    = javascript_include_tag "application", "data-turbolinks-track" => true
  - stylesheets do
    = stylesheet_link_tag "application"

  = render 'layouts/secondary_nav'
  - page_header "Megatron Documentation"

server/app/views/layouts/demo.html.slim
= megatron_layout(primary_nav: 'deployments') do
  - page_header "Megatron"

server/app/views/pages/buttons.html.slim
- main_header "Buttons"

- main
  p Buttons can be a links or true <code>&lt;button></code> tags.

  code: ruby
    # Basic button usage
    button 'Text', [options]

    # options:
    href: ''        # Make button a link
    type: :type     # :primary, :destroy, :primary_destroy, :text
    color: :color   # :green, :dark, :blue_outline, :green_outline, :dark_outline
    size: :size     # :small, :medium, :large, :xlarge
    disabled: false

  p 
    'When there are several forms on a single page, use a standard button type.
    'A primary button should be used as the default submission button for a large form, usually when that is the only form on the page.
  p You can use a button type healper instead of passing the type as an option.

  = demo_box "types", padded: false
    .demo-box-row
      = button 'Normal'
      = button 'Normal', disabled: true
    .demo-box-row
      = button 'Link', href: '#'
      = button 'Link', href: '#', disabled: true
    .demo-box-row
      = primary_button 'Primary'
      = primary_button 'Primary', disabled: true
    .demo-box-row
      = destroy_button 'Destroy'
      = destroy_button 'Destroy', disabled: true
    .demo-box-row
      = primary_destroy_button 'Primary Destroy'
      = primary_destroy_button 'Primary Destroy', disabled: true
    .demo-box-row
      = text_button 'Text Button'
      = text_button 'Text Button', disabled: true

  p Use the text button to provide an alternative action.

  = demo_box "Sample text button usage" do
    = text_button 'Cancel'
    = primary_button 'Save Changes'

  = heading 'Button Options'

  p There are only a few color options for buttons, here's a look.

  = demo_box "Colors" do
    = button ':green', color: :green
    = button ':dark', color: :dark
    = button ':blue_outline', color: :blue_outline
    = button ':green_outline', color: :green_outline
    = button ':dark_outline', color: :dark_outline

  p Set the size option for different size buttons. Here's a preview.

  = demo_box "Sizes" do
    = button ':small', size: :small
    = button ':medium', size: :medium
    = button 'default'
    = button ':large', size: :large
    = button ':xlarge', size: :xlarge

  = heading "Pills"
  markdown:
    Use a pill to call attention to a small scraps of important text. 

    - They are not buttons.
    - Pills shouldn't be more than two words.
    - There shouldn't be many on the same page.

    Any color from the [color palette](color) will work. Here's a demo:

  = demo_box "Pills" do
    span.pink-pill .pink-pill
    span.red-pill .red-pill
    span.orange-pill .orange-pill
    span.yellow-pill .yellow-pill
    span.green-pill .green-pill
    span.blue-pill .blue-pill
    span.purple-pill .purple-pill
    span.black-pill .black-pill

  = demo_box "Outline Pills" do
    span.pink-outline-pill .pink-outline-pill
    span.red-outline-pill .red-outline-pill
    span.orange-outline-pill .orange-outline-pill
    span.yellow-outline-pill .yellow-outline-pill
    span.green-outline-pill .green-outline-pill
    span.blue-outline-pill .blue-outline-pill
    span.purple-outline-pill .purple-outline-pill
    span.black-outline-pill .black-outline-pill


  = heading 'Copy Button'

  p Use a copy button to make it easy to copy the contents of some element to the clipboard.

  = demo_box "Copy button" do
    
    input#test-copy type='text' readonly='true' value="Copy this text"
    = copy_button 'Copy', target: '#test-copy'

server/app/views/pages/color.html.slim
- main_header "Color Palette"

- main do
  p Colors are good mkay?

  - path = File.expand_path(File.join(__dir__, '../../../../app/assets/stylesheets/megatron/modules/core/_colors.scss'))
  - parser = Sass::SCSS::Parser.new(File.read(path), '_colors.scss', Sass::Importers::Filesystem.new(File.expand_path(__FILE__))).parse


  - full_palette = nil
  - parser.each { |node| full_palette = node if node.is_a?(Sass::Tree::VariableNode) && node.name == 'full-palette' }

  table.box-table
    thead
      th
      th name
    tbody
      - full_palette.expr.pairs.map(&:first).map {|n| n.value.to_s.gsub('"', '') }.each do |name|
        tr
          td class="#{name}-bg"
          td = name


  / table.box-table
  /   thead

  /   .tile_label white
  /   .white-bg 
  /   .color-code #fff
  /   .tile_label softwhite
  /   .softwhite-bg 
  /   .color-code #fbfbfb
  /   .tile_label offwhite
  /   .offwhite-bg 
  /   .color-code #f5f6f6
  /   .tile_label silver
  /   .silver-bg 
  /   .color-code #edefef
  /   .tile_label overcast
  /   .overcast-bg 
  /   .color-code #dadede
  /   .tile_label lightgray
  /   .lightgray-bg 
  /   .color-code #b3b9bc
  /   .tile_label gray
  /   .gray-bg 
  /   .color-code #8d9297
  /   .tile_label mediumgray
  /   .mediumgray-bg 
  /   .color-code #666
  /   .tile_label darkgray
  /   .darkgray-bg 
  /   .color-code #444
  /   .tile_label slate
  /   .slate-bg 
  /   .color-code #788392
  /   .tile_label bluegray
  /   .bluegray-bg 
  /   .color-code #5e6b77
  /   .tile_label shade
  /   .shade-bg 
  /   .color-code #47515b
  /   .tile_label night
  /   .night-bg 
  /   .color-code #2d333b
  /   .tile_label space
  /   .space-bg 
  /   .color-code #262b30
  /   .tile_label black
  /   .black-bg 
  /   .color-code #000
  /   .tile_label boldred
  /   .boldred-bg 
  /   .color-code #df192a
  /   .tile_label red
  /   .red-bg 
  /   .color-code #cb413a
  /   .tile_label palered
  /   .palered-bg 
  /   .color-code #e46767
  /   .tile_label pink
  /   .pink-bg 
  /   .color-code #ff2d55
  /   .tile_label softred
  /   .softred-bg 
  /   .color-code #f7d4d4
  /   .tile_label orange
  /   .orange-bg 
  /   .color-code #ff9500
  /   .tile_label paleorange
  /   .paleorange-bg 
  /   .color-code #e4a667
  /   .tile_label softorange
  /   .softorange-bg 
  /   .color-code #f7e8d4
  /   .tile_label yellow
  /   .yellow-bg 
  /   .color-code #fc0
  /   .tile_label softyellow
  /   .softyellow-bg 
  /   .color-code #f7f4d4
  /   .tile_label cream
  /   .cream-bg 
  /   .color-code #fef0bd
  /   .tile_label yellowwhite
  /   .yellowwhite-bg 
  /   .color-code #fffefa
  /   .tile_label green
  /   .green-bg 
  /   .color-code #2ab22e
  /   .tile_label softgreen
  /   .softgreen-bg 
  /   .color-code #d4f7e0
  /   .tile_label greenwhite
  /   .greenwhite-bg 
  /   .color-code #fafffa
  /   .tile_label darkblue
  /   .darkblue-bg 
  /   .color-code #427bc5
  /   .tile_label blue
  /   .blue-bg 
  /   .color-code #4a89dc
  /   .tile_label lightblue
  /   .lightblue-bg 
  /   .color-code #5d9cec
  /   .tile_label boyblue
  /   .boyblue-bg 
  /   .color-code #409bd9
  /   .tile_label babyblue
  /   .babyblue-bg 
  /   .color-code #82c1ed
  /   .tile_label paleblue
  /   .paleblue-bg 
  /   .color-code #79add2
  /   .tile_label softblue
  /   .softblue-bg 
  /   .color-code #d4eef7
  /   .tile_label bluewhite
  /   .bluewhite-bg 
  /   .color-code #f5fcff
  /   .tile_label purple
  /   .purple-bg 
  /   .color-code #8e55dd
  /   .tile_label lightpurple
  /   .lightpurple-bg 
  /   .color-code #967adc
  /   .tile_label softpurple
  /   .softpurple-bg 
  /   .color-code #e3d4f7

server/app/views/pages/forms.html.slim
- main_header "Forms"

- main
  p The form helpers are being reworked, this page will be updated as they are developed.

  = heading 'Check switch'

  .check-switch
    input.switch#check-switch-test type='checkbox' checked=true
    label for='check-switch-test' Enable

  .check-switch
    input.switch#check-switch-test-3 type='checkbox'
    label for='check-switch-test-3' Enable

  .check-switch
    input.switch#check-switch-test type='checkbox' disabled=true checked=true
    label for='check-switch-test-2' Enable

  .check-switch
    input.switch#check-switch-test-4 type='checkbox' disabled=true
    label for='check-switch-test-4' Enable

  = heading 'Slider (Range) Input'

  markdown:
    This component is powered by [compose-slider](https://github.com/compose-ui/slider) and a Rails view helper in Megatron.

  = heading :h5, 'Basic usage'

  code: slim
    = slider_input_tag 'name', [options]
    / Name should be the input name, eg. 'some_model[some_property]'

  = heading :h5, 'Options'

  = markdown_table
    | Option | Type/Value | Example & Description |
    |:-|:-|:-|
    | min                     | Default: `0`      | Set a min value |
    | max                     | Default: `100`    | Set a max value |
    | value                   | Default: `0`      | Set a starting value |
    | values                  | `Array`           | `[1, 2, 5, …]` - Use custom values to set arbitrary values on a hidden input. <br> By default slider inputs can only have number values (min - max) |
    | before                  | `String`          | `'$'` - Put a `$` before the label.
    | after                   | `String`          | `'GB'` - Put `GB` after the label.
    | mark                    | `Array`           | `[1, 5, 10]` - Mark the first, fifth and 10th points. |
    | labels                  | `Array` or `Hash` | `{ disk: ['1GB, '2GB', …], price: ['$15', '$20', …] }` - Show custom labels. Use a hash for multiline labels. |
    | external_labels         | `Hash`            | `{ ram: ['256GB', '512GB', …] }` - Set contents of elements with `data-slider-label='ram'`. |
    | line_labels             | `Array`           | `[0: '1GB', 9: '256GB']` - Set a permanent "floating" label on the 1st and 10th point on the slider. |

  p Note: It's a bit of a hack, but if you use `big` or `small` in your hash keys for `labels` it will affect the label font size.

  = heading 'Demos'

  = demo_box "A simple slider"
    = slider_input_tag 'number'

  = demo_box "Slider with after label and markings"
    = slider_input_tag 'percent', after: '%', mark: [1, 50, 100]

  p Each of the demos below is using the following data.

  code: ruby
    disk = ['1GB','2GB','5GB','15GB','50GB']
    price = ['$10/mo', '$20/mo', '$50/mo', '$1,500/mo', '$5,000/mo']

  - disk = ['1GB','2GB','5GB','15GB','50GB']
  - price = ['$10/mo', '$20/mo', '$50/mo', '$1,500/mo', '$5,000/mo']


  = demo_box "Slider with line labels"
    = slider_input_tag 'deployment1[units]', labels: disk, line_labels: {'1' => '1GB', '3' => '5GB', '5' => '50GB'}

  = demo_box "Slider with two labels (using size hack)"
    = slider_input_tag 'deployment2[units]', labels: { big_disk: disk, small_price: price }

  = demo_box "Slider with external labels and custom values"
    = slider_input_tag 'deployment3[units]', labels: { size: disk }, external_labels: { disk: disk, price: price }, values: [1, 2, 5, 15, 50], mark: [1,3,5]
    p With <strong data-slider-label='disk'></strong> your price will be <strong data-slider-label='price'></strong>.
    p.help-text Use the web inspector and you'll see a hidden input being updated as the slider changes.

server/app/views/pages/grid/_cell_sizes.html.slim
= heading "Cell Sizing"
p Megatron ships with a sixths-based grid, meaning that the smallest size available is <strong>16.667%</strong>, or one-sixth. However, you can easily extend these. Depicted below are the available width classes.

.cell-size-demo
  = demo_box "Cell Sizes"
    - grid gutters: :none do |g|
      = g.cell 1, 6
        code=width(1, 6)
      = g.cell 5, 6, class: 'text-right'
        code=width(5, 6)

      = g.cell 1, 5
        code=width(1, 5)
      = g.cell 4, 5, class: 'text-right'
        code=width(4, 5)

      = g.cell 1, 4
        code=width(1, 4)
      = g.cell 3, 4, class: 'text-right'
        code=width(3, 4)

      = g.cell 1, 3
        code=width(1, 3)
      = g.cell 2, 3, class: 'text-right'
        code=width(2, 3)

      = g.cell 2, 5
        code=width(2, 5)
      = g.cell 3, 5, class: 'text-right'
        code=width(3, 5)

      = g.cell 1, 2
        code=width(1, 2)
      = g.cell 1, 2, class: 'text-right'
        code=width(1, 2)

      = g.cell 3, 5
        code=width(3, 5)
      = g.cell 2, 5, class: 'text-right'
        code=width(2, 5)

      = g.cell 2, 3
        code=width(2, 3)
      = g.cell 1, 3, class: 'text-right'
        code=width(1, 3)

      = g.cell 3, 4
        code=width(3, 4)
      = g.cell 1, 4, class: 'text-right'
        code=width(1, 4)

      = g.cell 4, 5
        code=width(4, 5)
      = g.cell 1, 5, class: 'text-right'
        code=width(1, 5)

      = g.cell 5, 6
        code=width(5, 6)
      = g.cell 1, 6, class: 'text-right'
        code=width(1, 6)

      = g.cell
        code grid-cell

server/app/views/pages/grid/_gutter_matching.html.slim
= heading 'Gutter Matching'
p By default grid gutters allow the margin of their contents to "leak" out and affect the vertical position of other grid cells. Here's an example where a <code>&lt;p></code> tag pushes the grid cells apart with margin.

.cell-size-demo
  = demo_box "\"Leaky\" Gutters (default)", padded: false
    .demo-box-row
      - grid match_gutters: false, gutters: :none do |g|
        = g.cell 1,3
          p: code=width 1,3
        = g.cell 2,3
          p: code=width 2,3
        = g.cell 3,5
          p: code=width 3,5
        = g.cell 2,5
          p: code=width 2,5
    .demo-box-row
      - grid match_gutters: false, gutters: :small do |g|
        = g.cell 1,3
          p: code=width 1,3
        = g.cell 2,3
          p: code=width 2,3
        = g.cell 3,5
          p: code=width 3,5
        = g.cell 2,5
          p: code=width 2,5
    .demo-box-row
      - grid match_gutters: false do |g|
        = g.cell 1,3
          p: code=width 1,3
        = g.cell 2,3
          p: code=width 2,3
        = g.cell 3,5
          p: code=width 3,5
        = g.cell 2,5
          p: code=width 2,5

p To prevent margins from leaking, set <code>match_gutters: true</code> and your grid's vertical and horizontal gutters will match. Here's a look.

.cell-size-demo
  = demo_box "Matching Gutters", padded: false
    .demo-box-row
      - grid match_gutters: true, gutters: :none do |g|
        = g.cell 1,3
          p: code=width 1,3
        = g.cell 2,3
          p: code=width 2,3
        = g.cell 3,5
          p: code=width 3,5
        = g.cell 2,5
          p: code=width 2,5
    .demo-box-row
      - grid match_gutters: true, gutters: :small do |g|
        = g.cell 1,3
          p: code=width 1,3
        = g.cell 2,3
          p: code=width 2,3
        = g.cell 3,5
          p: code=width 3,5
        = g.cell 2,5
          p: code=width 2,5
    .demo-box-row
      - grid match_gutters: true do |g|
        = g.cell 1,3
          p: code=width 1,3
        = g.cell 2,3
          p: code=width 2,3
        = g.cell 3,5
          p: code=width 3,5
        = g.cell 2,5
          p: code=width 2,5

server/app/views/pages/grid/_gutter_sizes.html.slim
= heading 'Gutter Sizing'

p By default, grid cells are given a 4% width gutter. Set the gutter size with the grid's <code>gutter</code> option.

code: slim
  - grid gutters: :none    # 0
  - grid gutters: :small   # 2%
  - grid                   # 4% (Default)
  - grid gutters: :large   # 8%

p Here's an example of each gutter width.

.gutter-demo
  = demo_box 'No Gutter'
    - grid gutters: :none do |g|
      = g.cell 1, 3
        code=width(1,3)
      = g.cell 1, 3
        code=width(1,3)
      = g.cell 1, 3
        code=width(1,3)

  = demo_box 'Small Gutter'
    - grid gutters: :small do |g|
      = g.cell 1, 3
        code=width(1,3)
      = g.cell 1, 3
        code=width(1,3)
      = g.cell 1, 3
        code=width(1,3)

  = demo_box 'Default Gutter'
    - grid do |g|
      = g.cell 1, 3
        code=width(1,3)
      = g.cell 1, 3
        code=width(1,3)
      = g.cell 1, 3
        code=width(1,3)

  = demo_box 'Large Gutter'
    - grid gutters: :large do |g|
      = g.cell 1, 3
        code=width(1,3)
      = g.cell 1, 3
        code=width(1,3)
      = g.cell 1, 3
        code=width(1,3)

server/app/views/pages/grid/_horizontal_alignment.html.slim
= heading "Horizontal Alignment"

p By default, grid cells are left aligned. To center or right-align them, set the <code>align</code> grid option. This will align all nested grid cells.

code: slim
  - grid align: :right  
  - grid align: :center

= demo_box 'Left alignment (default)'
  - grid match_gutters: true, gutters: :small do |g|
    = g.cell 1,3
      code=width 1,3
    = g.cell 1,3
      code=width 1,3
    = g.cell
      code grid-cell
    = g.cell 1,4
      code=width 1,4
    = g.cell 1,4
      code=width 1,4
    = g.cell 1,4
      code=width 1,4

= demo_box 'Right alignment'
  - grid align: :right, match_gutters: true, gutters: :small do |g|
    = g.cell 1,3
      code=width 1,3
    = g.cell 1,3
      code=width 1,3
    = g.cell
      code grid-cell
    = g.cell 1,4
      code=width 1,4
    = g.cell 1,4
      code=width 1,4
    = g.cell 1,4
      code=width 1,4

= demo_box 'Center alignment'
  - grid align: :center, match_gutters: true, gutters: :small do |g|
    = g.cell 1,3
      code=width 1,3
    = g.cell 1,3
      code=width 1,3
    = g.cell
      code grid-cell
    = g.cell 1,4
      code=width 1,4
    = g.cell 1,4
      code=width 1,4
    = g.cell 1,4
      code=width 1,4

server/app/views/pages/grid/_nested_grids.html.slim
= heading "Nested Grids"

p Want to get all Xzibit and put a grid inside another grid so you can grid while you grid? Go for it. Here's how it looks.

= demo_box 'Nested Grid'
  - grid gutters: :small, match_gutters: true do |g|
    = g.cell 2, 5
      code=width(2,5)
    = g.cell 3, 5
      - grid gutters: :small, match_gutters: true do |gg|
        = gg.cell 1, 2
          code=width(1,2)
        = gg.cell 1, 2
          code=width(1,2)
        = gg.cell 1, 3
          code=width(1,3)
        = gg.cell 1, 3
          code=width(1,3)

server/app/views/pages/grid/_responsive_cell_sizes.html.slim
= heading "Responsive Cell Sizing"
p Grid cells sizes can be set based on predefined browser size breakpoints. 

code: slim
  - grid do |g|
    /sizes:  450px          600px         750px          900px         1200px
    = g.cell xsmall: [1,2], small: [1,3], medium: [1,4], large: [1,5], xlarge: [1,6]

p Here's a demo. Resize your browser to see the grid cells realign themselves

.cell-size-demo
  = demo_box "Responsive Cell Sizes"
    - args = { xsmall: [1,2], small: [1,3], medium: [1,4], large: [1,5], xlarge: [1,6] }
    - grid gutters: :small do |g|
      = g.cell args
        code test
      = g.cell args
        code test
      = g.cell args
        code test
      = g.cell args
        code test
      = g.cell args
        code test
      = g.cell args
        code test
      = g.cell args
        code test
      = g.cell args
        code test

server/app/views/pages/grid/_vertical_alignment.html.slim
= heading "Vertical Alignment"

p By default, grid cells are top aligned. To align grids to the middle or bottom them, set the <code>valign</code> grid option. This will align all nested grid cells.

code: slim
  - grid valign: :middle  
  - grid valign: :bottom

= demo_box 'Top alignment (default)'
  - grid match_gutters: true, gutters: :small do |g|
    = g.cell 1,3
      h3 Lorem Ipsum Dolor
    = g.cell 2,3
      p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

= demo_box 'Middle alignment'
  - grid valign: :middle, match_gutters: true, gutters: :small do |g|
    = g.cell 1,3
      h3 Lorem Ipsum Dolor
    = g.cell 2,3
      p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

= demo_box 'Center alignment'
  - grid valign: :bottom, match_gutters: true, gutters: :small do |g|
    = g.cell 1,3
      h3 Lorem Ipsum Dolor
    = g.cell 2,3
      p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

server/app/views/pages/grids.html.slim
- main_header
  h2 Grids

- main
  /- tabs do |t|
    /= t.tab 'Grids', '/grids'
    /= t.tab 'Boxes', '/boxes'

  .grid-demo
    = heading "Using Grids"
    code: slim
      - grid [options] do |g|       # You'll use the grid block
        = g.cell [size], [options]  # and grid cells
          p Content!
    
    = heading "Grid/Cell Options"

    p Grid blocks can accept these options (defaults are listed first).

    code: ruby
      gutters: 'medium', 'none', 'small', 'large'
      gutter_matching: false, true
      align:   'left', 'center', 'right'
      valign:  'top', 'middle', 'bottom'
      
    p Cells accept an optional size followed by a hash of options.

    code: ruby
      g.cell [1,2], [options]

      # responsive size options
      xsmall: []
      small:  []
      medium: []
      large:  []
      xlarge: []

    p Here's an example:

    = demo_box 'Simple grid'
      - grid do |g|
        = g.cell
          code grid-cell
        = g.cell [1, 3]
          code=width(1,3)
        = g.cell [1, 3]
          code=width(1,3)
        = g.cell [1, 3]
          code=width(1,3)

    = render "pages/grid/cell_sizes"
    = render "pages/grid/responsive_cell_sizes"
    = render "pages/grid/gutter_sizes"
    = render "pages/grid/gutter_matching"
    = render "pages/grid/nested_grids"
    = render "pages/grid/horizontal_alignment"
    = render "pages/grid/vertical_alignment"